event:
  title_en: "PhD Party"
  title_it: "PhD Party"
  subtitle_en: "Join us to celebrate the completion of our PhD studies"
  subtitle_it: "Unisciti a noi per celebrare il conseguimento del nostro dottorato"
  graduants:
    - "Domenico Campanaro"
    - "Luigi Campanaro"
  
  welcome_message_en: "We are delighted to share this milestone with our family and friends. Thank you for your support; we can't wait to celebrate with you."
  welcome_message_it: "Siamo felici di condividere questo traguardo con la nostra famiglia ed i nostri amici. Grazie per il vostro supporto, non vediamo l'ora di festeggiare con voi."

venue:
  name: "Njlaya Club"
  address: "Via Chico Mendes, 70125 Bari BA, Italia"
  google_maps_link: "https://share.google/Aw4j01IkH0LHIwQnd"

date_time:
  date_en: "December 28, 2025"
  date_it: "28 Dicembre 2025"
  time: "20:00 - 02:00"

rsvp:
  cta_en: "Confirm Your Attendance"
  cta_it: "Conferma la Tua Presenza"
  deadline_en: "Please RSVP by December 18th, 2025"
  deadline_it: "Si prega di confermare entro il 18 Dicembre 2025"
